version: "3"
services:
   mongo:
      image: "mongo:latest"
      volumes:
         - "${MONGO_VOLUME:-mongo-mayf-photo}:/data/db"
   apache:
      build: .
      image: "mayf-photo"
      volumes:
         - "${PHOTO_DIR:-/var/www/html/Home}:/var/www/html/Home"
         - "${THUMB_DIR:-/var/www/html/thumbs}:/var/www/html/thumbs"
      ports:
         - "${MAYF_PORT:-789}:80"
   cron:
      image: "jobber"
      volumes:
         - "./cron:/home/jobberuser/"
volumes:
   mongo-mayf-photo:
